jobs:
  test:
    name: fast test on Java ${{ matrix.java }} OS ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -V --no-transfer-progress clean install
    - continue-on-error: true
      if: runner.os != 'Windows'
      name: remove cola self maven install files for OS *nix
      run: rm -rf $HOME/.m2/repository/com/alibaba/{cola,craftsman}
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: remove cola self maven install files for OS Windows
      run: 'Remove-Item -Recurse -Force $home/.m2/repository/com/alibaba/cola

        Remove-Item -Recurse -Force $home/.m2/repository/com/alibaba/craftsman

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
        - windows-latest
      max-parallel: 64
    timeout-minutes: 10
name: Fast CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
