jobs:
  test:
    name: test by multiply java versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '17

          21

          22

          '
    - continue-on-error: true
      env:
        JAVA17_HOME: ${{ env.JAVA_HOME_17_X64 }}
        JAVA21_HOME: ${{ env.JAVA_HOME_21_X64 }}
        JAVA22_HOME: ${{ env.JAVA_HOME_22_X64 }}
      run: scripts/integration_test
    - continue-on-error: true
      name: remove cola self maven install files
      run: rm -rf $HOME/.m2/repository/com/alibaba/{cola,craftsman}
    timeout-minutes: 20
name: Strong CI with multiply java versions
on:
  repository_dispatch:
    types: trigger-ga___ci_by_multiply_java_versions.yaml
